version: '3.7'
services:

    postgres:
        image: postgres:12.2
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: jpa-filter
        ports:
            - "5432:5432"

# volumes:
    # pgdata:
        # driver: local
        # name: "pgdata"

#networks:
#    appnet:
#        driver: bridge
#        name: "appnet"
